server:
  port: 9003
spring:
  application:
    name: jwjung-board-view-service
  datasource:
    url: jdbc:mysql://localhost:3306/article_view
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1
      port: 6380
  kafka:
    bootstrap-servers: 127.0.0.1:9092