server:
  port: 9005
spring:
  application:
    name: jwjung-board-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6380
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jwjung-board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
endpoints:
  jwjung-board-article-service:
    url: http://127.0.0.1:8999
  jwjung-board-comment-service:
    url: http://127.0.0.1:9001
  jwjung-board-like-service:
    url: http://127.0.0.1:9002
  jwjung-board-view-service:
    url: http://127.0.0.1:9003