server:
  port: 9000
spring:
  application:
    name: jwjung-board-article-service
  datasource:
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none